// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/zone/zone.proto

package zone

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Zone struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgId          string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Mode           string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"` // "test" | "live"
	SecretKey      string                 `protobuf:"bytes,5,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	PublishableKey string                 `protobuf:"bytes,6,opt,name=publishable_key,json=publishableKey,proto3" json:"publishable_key,omitempty"`
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	TemplateName   string                 `protobuf:"bytes,8,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt      string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Zone) Reset() {
	*x = Zone{}
	mi := &file_proto_zone_zone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone) ProtoMessage() {}

func (x *Zone) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zone_zone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone.ProtoReflect.Descriptor instead.
func (*Zone) Descriptor() ([]byte, []int) {
	return file_proto_zone_zone_proto_rawDescGZIP(), []int{0}
}

func (x *Zone) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Zone) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Zone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Zone) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Zone) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *Zone) GetPublishableKey() string {
	if x != nil {
		return x.PublishableKey
	}
	return ""
}

func (x *Zone) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Zone) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *Zone) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Zone) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	TemplateName  string                 `protobuf:"bytes,4,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateZoneRequest) Reset() {
	*x = CreateZoneRequest{}
	mi := &file_proto_zone_zone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateZoneRequest) ProtoMessage() {}

func (x *CreateZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zone_zone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateZoneRequest.ProtoReflect.Descriptor instead.
func (*CreateZoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_zone_zone_proto_rawDescGZIP(), []int{1}
}

func (x *CreateZoneRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CreateZoneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateZoneRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CreateZoneRequest) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *CreateZoneRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetZoneRequest) Reset() {
	*x = GetZoneRequest{}
	mi := &file_proto_zone_zone_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetZoneRequest) ProtoMessage() {}

func (x *GetZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zone_zone_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetZoneRequest.ProtoReflect.Descriptor instead.
func (*GetZoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_zone_zone_proto_rawDescGZIP(), []int{2}
}

func (x *GetZoneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListZonesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListZonesRequest) Reset() {
	*x = ListZonesRequest{}
	mi := &file_proto_zone_zone_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListZonesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListZonesRequest) ProtoMessage() {}

func (x *ListZonesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zone_zone_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListZonesRequest.ProtoReflect.Descriptor instead.
func (*ListZonesRequest) Descriptor() ([]byte, []int) {
	return file_proto_zone_zone_proto_rawDescGZIP(), []int{3}
}

func (x *ListZonesRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type ListZonesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zones         []*Zone                `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListZonesResponse) Reset() {
	*x = ListZonesResponse{}
	mi := &file_proto_zone_zone_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListZonesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListZonesResponse) ProtoMessage() {}

func (x *ListZonesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zone_zone_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListZonesResponse.ProtoReflect.Descriptor instead.
func (*ListZonesResponse) Descriptor() ([]byte, []int) {
	return file_proto_zone_zone_proto_rawDescGZIP(), []int{4}
}

func (x *ListZonesResponse) GetZones() []*Zone {
	if x != nil {
		return x.Zones
	}
	return nil
}

type UpdateZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateZoneRequest) Reset() {
	*x = UpdateZoneRequest{}
	mi := &file_proto_zone_zone_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateZoneRequest) ProtoMessage() {}

func (x *UpdateZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zone_zone_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateZoneRequest.ProtoReflect.Descriptor instead.
func (*UpdateZoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_zone_zone_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateZoneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateZoneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateZoneRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateZoneRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type BulkUpdateMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneIds       []string               `protobuf:"bytes,1,rep,name=zone_ids,json=zoneIds,proto3" json:"zone_ids,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkUpdateMetadataRequest) Reset() {
	*x = BulkUpdateMetadataRequest{}
	mi := &file_proto_zone_zone_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkUpdateMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkUpdateMetadataRequest) ProtoMessage() {}

func (x *BulkUpdateMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zone_zone_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkUpdateMetadataRequest.ProtoReflect.Descriptor instead.
func (*BulkUpdateMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_zone_zone_proto_rawDescGZIP(), []int{6}
}

func (x *BulkUpdateMetadataRequest) GetZoneIds() []string {
	if x != nil {
		return x.ZoneIds
	}
	return nil
}

func (x *BulkUpdateMetadataRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type BulkUpdateMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedCount  int32                  `protobuf:"varint,1,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkUpdateMetadataResponse) Reset() {
	*x = BulkUpdateMetadataResponse{}
	mi := &file_proto_zone_zone_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkUpdateMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkUpdateMetadataResponse) ProtoMessage() {}

func (x *BulkUpdateMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zone_zone_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkUpdateMetadataResponse.ProtoReflect.Descriptor instead.
func (*BulkUpdateMetadataResponse) Descriptor() ([]byte, []int) {
	return file_proto_zone_zone_proto_rawDescGZIP(), []int{7}
}

func (x *BulkUpdateMetadataResponse) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

var File_proto_zone_zone_proto protoreflect.FileDescriptor

const file_proto_zone_zone_proto_rawDesc = "" +
	"\n" +
	"\x15proto/zone/zone.proto\x12\x04zone\x1a\x1cgoogle/api/annotations.proto\"\xec\x02\n" +
	"\x04Zone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x05 \x01(\tR\tsecretKey\x12'\n" +
	"\x0fpublishable_key\x18\x06 \x01(\tR\x0epublishableKey\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12#\n" +
	"\rtemplate_name\x18\b \x01(\tR\ftemplateName\x124\n" +
	"\bmetadata\x18\t \x03(\v2\x18.zone.Zone.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf7\x01\n" +
	"\x11CreateZoneRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12#\n" +
	"\rtemplate_name\x18\x04 \x01(\tR\ftemplateName\x12A\n" +
	"\bmetadata\x18\x05 \x03(\v2%.zone.CreateZoneRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\" \n" +
	"\x0eGetZoneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\x10ListZonesRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\"5\n" +
	"\x11ListZonesResponse\x12 \n" +
	"\x05zones\x18\x01 \x03(\v2\n" +
	".zone.ZoneR\x05zones\"\xcf\x01\n" +
	"\x11UpdateZoneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12A\n" +
	"\bmetadata\x18\x04 \x03(\v2%.zone.UpdateZoneRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbe\x01\n" +
	"\x19BulkUpdateMetadataRequest\x12\x19\n" +
	"\bzone_ids\x18\x01 \x03(\tR\azoneIds\x12I\n" +
	"\bmetadata\x18\x02 \x03(\v2-.zone.BulkUpdateMetadataRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\x1aBulkUpdateMetadataResponse\x12#\n" +
	"\rupdated_count\x18\x01 \x01(\x05R\fupdatedCount2\xb7\x03\n" +
	"\vZoneService\x12G\n" +
	"\n" +
	"CreateZone\x12\x17.zone.CreateZoneRequest\x1a\n" +
	".zone.Zone\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/zones\x12C\n" +
	"\aGetZone\x12\x14.zone.GetZoneRequest\x1a\n" +
	".zone.Zone\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/zones/{id}\x12O\n" +
	"\tListZones\x12\x16.zone.ListZonesRequest\x1a\x17.zone.ListZonesResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/zones\x12L\n" +
	"\n" +
	"UpdateZone\x12\x17.zone.UpdateZoneRequest\x1a\n" +
	".zone.Zone\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/zones/{id}\x12{\n" +
	"\x12BulkUpdateMetadata\x12\x1f.zone.BulkUpdateMetadataRequest\x1a .zone.BulkUpdateMetadataResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/zones/bulk-metadataB0Z.github.com/sapliy/sapliy-core/proto/zoneb\x06proto3"

var (
	file_proto_zone_zone_proto_rawDescOnce sync.Once
	file_proto_zone_zone_proto_rawDescData []byte
)

func file_proto_zone_zone_proto_rawDescGZIP() []byte {
	file_proto_zone_zone_proto_rawDescOnce.Do(func() {
		file_proto_zone_zone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_zone_zone_proto_rawDesc), len(file_proto_zone_zone_proto_rawDesc)))
	})
	return file_proto_zone_zone_proto_rawDescData
}

var file_proto_zone_zone_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_zone_zone_proto_goTypes = []any{
	(*Zone)(nil),                       // 0: zone.Zone
	(*CreateZoneRequest)(nil),          // 1: zone.CreateZoneRequest
	(*GetZoneRequest)(nil),             // 2: zone.GetZoneRequest
	(*ListZonesRequest)(nil),           // 3: zone.ListZonesRequest
	(*ListZonesResponse)(nil),          // 4: zone.ListZonesResponse
	(*UpdateZoneRequest)(nil),          // 5: zone.UpdateZoneRequest
	(*BulkUpdateMetadataRequest)(nil),  // 6: zone.BulkUpdateMetadataRequest
	(*BulkUpdateMetadataResponse)(nil), // 7: zone.BulkUpdateMetadataResponse
	nil,                                // 8: zone.Zone.MetadataEntry
	nil,                                // 9: zone.CreateZoneRequest.MetadataEntry
	nil,                                // 10: zone.UpdateZoneRequest.MetadataEntry
	nil,                                // 11: zone.BulkUpdateMetadataRequest.MetadataEntry
}
var file_proto_zone_zone_proto_depIdxs = []int32{
	8,  // 0: zone.Zone.metadata:type_name -> zone.Zone.MetadataEntry
	9,  // 1: zone.CreateZoneRequest.metadata:type_name -> zone.CreateZoneRequest.MetadataEntry
	0,  // 2: zone.ListZonesResponse.zones:type_name -> zone.Zone
	10, // 3: zone.UpdateZoneRequest.metadata:type_name -> zone.UpdateZoneRequest.MetadataEntry
	11, // 4: zone.BulkUpdateMetadataRequest.metadata:type_name -> zone.BulkUpdateMetadataRequest.MetadataEntry
	1,  // 5: zone.ZoneService.CreateZone:input_type -> zone.CreateZoneRequest
	2,  // 6: zone.ZoneService.GetZone:input_type -> zone.GetZoneRequest
	3,  // 7: zone.ZoneService.ListZones:input_type -> zone.ListZonesRequest
	5,  // 8: zone.ZoneService.UpdateZone:input_type -> zone.UpdateZoneRequest
	6,  // 9: zone.ZoneService.BulkUpdateMetadata:input_type -> zone.BulkUpdateMetadataRequest
	0,  // 10: zone.ZoneService.CreateZone:output_type -> zone.Zone
	0,  // 11: zone.ZoneService.GetZone:output_type -> zone.Zone
	4,  // 12: zone.ZoneService.ListZones:output_type -> zone.ListZonesResponse
	0,  // 13: zone.ZoneService.UpdateZone:output_type -> zone.Zone
	7,  // 14: zone.ZoneService.BulkUpdateMetadata:output_type -> zone.BulkUpdateMetadataResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_zone_zone_proto_init() }
func file_proto_zone_zone_proto_init() {
	if File_proto_zone_zone_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_zone_zone_proto_rawDesc), len(file_proto_zone_zone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_zone_zone_proto_goTypes,
		DependencyIndexes: file_proto_zone_zone_proto_depIdxs,
		MessageInfos:      file_proto_zone_zone_proto_msgTypes,
	}.Build()
	File_proto_zone_zone_proto = out.File
	file_proto_zone_zone_proto_goTypes = nil
	file_proto_zone_zone_proto_depIdxs = nil
}
