// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/notifications/notifications.proto

package notifications

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWebhookEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	EnabledEvents []string               `protobuf:"bytes,2,rep,name=enabled_events,json=enabledEvents,proto3" json:"enabled_events,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWebhookEndpointRequest) Reset() {
	*x = CreateWebhookEndpointRequest{}
	mi := &file_proto_notifications_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWebhookEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebhookEndpointRequest) ProtoMessage() {}

func (x *CreateWebhookEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifications_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebhookEndpointRequest.ProtoReflect.Descriptor instead.
func (*CreateWebhookEndpointRequest) Descriptor() ([]byte, []int) {
	return file_proto_notifications_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWebhookEndpointRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateWebhookEndpointRequest) GetEnabledEvents() []string {
	if x != nil {
		return x.EnabledEvents
	}
	return nil
}

func (x *CreateWebhookEndpointRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type WebhookEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	EnabledEvents []string               `protobuf:"bytes,3,rep,name=enabled_events,json=enabledEvents,proto3" json:"enabled_events,omitempty"`
	Secret        string                 `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookEndpoint) Reset() {
	*x = WebhookEndpoint{}
	mi := &file_proto_notifications_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEndpoint) ProtoMessage() {}

func (x *WebhookEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifications_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEndpoint.ProtoReflect.Descriptor instead.
func (*WebhookEndpoint) Descriptor() ([]byte, []int) {
	return file_proto_notifications_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *WebhookEndpoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebhookEndpoint) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebhookEndpoint) GetEnabledEvents() []string {
	if x != nil {
		return x.EnabledEvents
	}
	return nil
}

func (x *WebhookEndpoint) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *WebhookEndpoint) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WebhookEndpoint) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListWebhookEndpointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhookEndpointsRequest) Reset() {
	*x = ListWebhookEndpointsRequest{}
	mi := &file_proto_notifications_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhookEndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhookEndpointsRequest) ProtoMessage() {}

func (x *ListWebhookEndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifications_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhookEndpointsRequest.ProtoReflect.Descriptor instead.
func (*ListWebhookEndpointsRequest) Descriptor() ([]byte, []int) {
	return file_proto_notifications_notifications_proto_rawDescGZIP(), []int{2}
}

type ListWebhookEndpointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*WebhookEndpoint     `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhookEndpointsResponse) Reset() {
	*x = ListWebhookEndpointsResponse{}
	mi := &file_proto_notifications_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhookEndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhookEndpointsResponse) ProtoMessage() {}

func (x *ListWebhookEndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifications_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhookEndpointsResponse.ProtoReflect.Descriptor instead.
func (*ListWebhookEndpointsResponse) Descriptor() ([]byte, []int) {
	return file_proto_notifications_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *ListWebhookEndpointsResponse) GetEndpoints() []*WebhookEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type DeleteWebhookEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWebhookEndpointRequest) Reset() {
	*x = DeleteWebhookEndpointRequest{}
	mi := &file_proto_notifications_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebhookEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebhookEndpointRequest) ProtoMessage() {}

func (x *DeleteWebhookEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifications_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebhookEndpointRequest.ProtoReflect.Descriptor instead.
func (*DeleteWebhookEndpointRequest) Descriptor() ([]byte, []int) {
	return file_proto_notifications_notifications_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteWebhookEndpointRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteWebhookEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWebhookEndpointResponse) Reset() {
	*x = DeleteWebhookEndpointResponse{}
	mi := &file_proto_notifications_notifications_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebhookEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebhookEndpointResponse) ProtoMessage() {}

func (x *DeleteWebhookEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifications_notifications_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebhookEndpointResponse.ProtoReflect.Descriptor instead.
func (*DeleteWebhookEndpointResponse) Descriptor() ([]byte, []int) {
	return file_proto_notifications_notifications_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteWebhookEndpointResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetNotificationHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationHistoryRequest) Reset() {
	*x = GetNotificationHistoryRequest{}
	mi := &file_proto_notifications_notifications_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationHistoryRequest) ProtoMessage() {}

func (x *GetNotificationHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifications_notifications_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_notifications_notifications_proto_rawDescGZIP(), []int{6}
}

func (x *GetNotificationHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetNotificationHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetNotificationHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Recipient     string                 `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SentAt        string                 `protobuf:"bytes,9,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_proto_notifications_notifications_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifications_notifications_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_proto_notifications_notifications_proto_rawDescGZIP(), []int{7}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notification) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *Notification) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Notification) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Notification) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Notification) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

type GetNotificationHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationHistoryResponse) Reset() {
	*x = GetNotificationHistoryResponse{}
	mi := &file_proto_notifications_notifications_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationHistoryResponse) ProtoMessage() {}

func (x *GetNotificationHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifications_notifications_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_notifications_notifications_proto_rawDescGZIP(), []int{8}
}

func (x *GetNotificationHistoryResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

var File_proto_notifications_notifications_proto protoreflect.FileDescriptor

const file_proto_notifications_notifications_proto_rawDesc = "" +
	"\n" +
	"'proto/notifications/notifications.proto\x12\rnotifications\x1a\x1cgoogle/api/annotations.proto\"y\n" +
	"\x1cCreateWebhookEndpointRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12%\n" +
	"\x0eenabled_events\x18\x02 \x03(\tR\renabledEvents\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xa9\x01\n" +
	"\x0fWebhookEndpoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12%\n" +
	"\x0eenabled_events\x18\x03 \x03(\tR\renabledEvents\x12\x16\n" +
	"\x06secret\x18\x04 \x01(\tR\x06secret\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\x1d\n" +
	"\x1bListWebhookEndpointsRequest\"\\\n" +
	"\x1cListWebhookEndpointsResponse\x12<\n" +
	"\tendpoints\x18\x01 \x03(\v2\x1e.notifications.WebhookEndpointR\tendpoints\".\n" +
	"\x1cDeleteWebhookEndpointRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x1dDeleteWebhookEndpointResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"f\n" +
	"\x1dGetNotificationHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\xef\x01\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1c\n" +
	"\trecipient\x18\x03 \x01(\tR\trecipient\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x17\n" +
	"\asent_at\x18\t \x01(\tR\x06sentAt\"c\n" +
	"\x1eGetNotificationHistoryResponse\x12A\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1b.notifications.NotificationR\rnotifications2\xde\x04\n" +
	"\x13NotificationService\x12\x87\x01\n" +
	"\x15CreateWebhookEndpoint\x12+.notifications.CreateWebhookEndpointRequest\x1a\x1e.notifications.WebhookEndpoint\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/webhooks/endpoints\x12\x8f\x01\n" +
	"\x14ListWebhookEndpoints\x12*.notifications.ListWebhookEndpointsRequest\x1a+.notifications.ListWebhookEndpointsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/webhooks/endpoints\x12\x97\x01\n" +
	"\x15DeleteWebhookEndpoint\x12+.notifications.DeleteWebhookEndpointRequest\x1a,.notifications.DeleteWebhookEndpointResponse\"#\x82\xd3\xe4\x93\x02\x1d*\x1b/v1/webhooks/endpoints/{id}\x12\x90\x01\n" +
	"\x16GetNotificationHistory\x12,.notifications.GetNotificationHistoryRequest\x1a-.notifications.GetNotificationHistoryResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/notificationsB9Z7github.com/sapliy/sapliy-core/proto/notificationsb\x06proto3"

var (
	file_proto_notifications_notifications_proto_rawDescOnce sync.Once
	file_proto_notifications_notifications_proto_rawDescData []byte
)

func file_proto_notifications_notifications_proto_rawDescGZIP() []byte {
	file_proto_notifications_notifications_proto_rawDescOnce.Do(func() {
		file_proto_notifications_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notifications_notifications_proto_rawDesc), len(file_proto_notifications_notifications_proto_rawDesc)))
	})
	return file_proto_notifications_notifications_proto_rawDescData
}

var file_proto_notifications_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_notifications_notifications_proto_goTypes = []any{
	(*CreateWebhookEndpointRequest)(nil),   // 0: notifications.CreateWebhookEndpointRequest
	(*WebhookEndpoint)(nil),                // 1: notifications.WebhookEndpoint
	(*ListWebhookEndpointsRequest)(nil),    // 2: notifications.ListWebhookEndpointsRequest
	(*ListWebhookEndpointsResponse)(nil),   // 3: notifications.ListWebhookEndpointsResponse
	(*DeleteWebhookEndpointRequest)(nil),   // 4: notifications.DeleteWebhookEndpointRequest
	(*DeleteWebhookEndpointResponse)(nil),  // 5: notifications.DeleteWebhookEndpointResponse
	(*GetNotificationHistoryRequest)(nil),  // 6: notifications.GetNotificationHistoryRequest
	(*Notification)(nil),                   // 7: notifications.Notification
	(*GetNotificationHistoryResponse)(nil), // 8: notifications.GetNotificationHistoryResponse
}
var file_proto_notifications_notifications_proto_depIdxs = []int32{
	1, // 0: notifications.ListWebhookEndpointsResponse.endpoints:type_name -> notifications.WebhookEndpoint
	7, // 1: notifications.GetNotificationHistoryResponse.notifications:type_name -> notifications.Notification
	0, // 2: notifications.NotificationService.CreateWebhookEndpoint:input_type -> notifications.CreateWebhookEndpointRequest
	2, // 3: notifications.NotificationService.ListWebhookEndpoints:input_type -> notifications.ListWebhookEndpointsRequest
	4, // 4: notifications.NotificationService.DeleteWebhookEndpoint:input_type -> notifications.DeleteWebhookEndpointRequest
	6, // 5: notifications.NotificationService.GetNotificationHistory:input_type -> notifications.GetNotificationHistoryRequest
	1, // 6: notifications.NotificationService.CreateWebhookEndpoint:output_type -> notifications.WebhookEndpoint
	3, // 7: notifications.NotificationService.ListWebhookEndpoints:output_type -> notifications.ListWebhookEndpointsResponse
	5, // 8: notifications.NotificationService.DeleteWebhookEndpoint:output_type -> notifications.DeleteWebhookEndpointResponse
	8, // 9: notifications.NotificationService.GetNotificationHistory:output_type -> notifications.GetNotificationHistoryResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_notifications_notifications_proto_init() }
func file_proto_notifications_notifications_proto_init() {
	if File_proto_notifications_notifications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notifications_notifications_proto_rawDesc), len(file_proto_notifications_notifications_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notifications_notifications_proto_goTypes,
		DependencyIndexes: file_proto_notifications_notifications_proto_depIdxs,
		MessageInfos:      file_proto_notifications_notifications_proto_msgTypes,
	}.Build()
	File_proto_notifications_notifications_proto = out.File
	file_proto_notifications_notifications_proto_goTypes = nil
	file_proto_notifications_notifications_proto_depIdxs = nil
}
