// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.0
// source: proto/notifications/notifications.proto

package notifications

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationService_CreateWebhookEndpoint_FullMethodName  = "/notifications.NotificationService/CreateWebhookEndpoint"
	NotificationService_ListWebhookEndpoints_FullMethodName   = "/notifications.NotificationService/ListWebhookEndpoints"
	NotificationService_DeleteWebhookEndpoint_FullMethodName  = "/notifications.NotificationService/DeleteWebhookEndpoint"
	NotificationService_GetNotificationHistory_FullMethodName = "/notifications.NotificationService/GetNotificationHistory"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	CreateWebhookEndpoint(ctx context.Context, in *CreateWebhookEndpointRequest, opts ...grpc.CallOption) (*WebhookEndpoint, error)
	ListWebhookEndpoints(ctx context.Context, in *ListWebhookEndpointsRequest, opts ...grpc.CallOption) (*ListWebhookEndpointsResponse, error)
	DeleteWebhookEndpoint(ctx context.Context, in *DeleteWebhookEndpointRequest, opts ...grpc.CallOption) (*DeleteWebhookEndpointResponse, error)
	GetNotificationHistory(ctx context.Context, in *GetNotificationHistoryRequest, opts ...grpc.CallOption) (*GetNotificationHistoryResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) CreateWebhookEndpoint(ctx context.Context, in *CreateWebhookEndpointRequest, opts ...grpc.CallOption) (*WebhookEndpoint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebhookEndpoint)
	err := c.cc.Invoke(ctx, NotificationService_CreateWebhookEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) ListWebhookEndpoints(ctx context.Context, in *ListWebhookEndpointsRequest, opts ...grpc.CallOption) (*ListWebhookEndpointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWebhookEndpointsResponse)
	err := c.cc.Invoke(ctx, NotificationService_ListWebhookEndpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) DeleteWebhookEndpoint(ctx context.Context, in *DeleteWebhookEndpointRequest, opts ...grpc.CallOption) (*DeleteWebhookEndpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWebhookEndpointResponse)
	err := c.cc.Invoke(ctx, NotificationService_DeleteWebhookEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetNotificationHistory(ctx context.Context, in *GetNotificationHistoryRequest, opts ...grpc.CallOption) (*GetNotificationHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNotificationHistoryResponse)
	err := c.cc.Invoke(ctx, NotificationService_GetNotificationHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility.
type NotificationServiceServer interface {
	CreateWebhookEndpoint(context.Context, *CreateWebhookEndpointRequest) (*WebhookEndpoint, error)
	ListWebhookEndpoints(context.Context, *ListWebhookEndpointsRequest) (*ListWebhookEndpointsResponse, error)
	DeleteWebhookEndpoint(context.Context, *DeleteWebhookEndpointRequest) (*DeleteWebhookEndpointResponse, error)
	GetNotificationHistory(context.Context, *GetNotificationHistoryRequest) (*GetNotificationHistoryResponse, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServiceServer struct{}

func (UnimplementedNotificationServiceServer) CreateWebhookEndpoint(context.Context, *CreateWebhookEndpointRequest) (*WebhookEndpoint, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWebhookEndpoint not implemented")
}
func (UnimplementedNotificationServiceServer) ListWebhookEndpoints(context.Context, *ListWebhookEndpointsRequest) (*ListWebhookEndpointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWebhookEndpoints not implemented")
}
func (UnimplementedNotificationServiceServer) DeleteWebhookEndpoint(context.Context, *DeleteWebhookEndpointRequest) (*DeleteWebhookEndpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWebhookEndpoint not implemented")
}
func (UnimplementedNotificationServiceServer) GetNotificationHistory(context.Context, *GetNotificationHistoryRequest) (*GetNotificationHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNotificationHistory not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}
func (UnimplementedNotificationServiceServer) testEmbeddedByValue()                             {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	// If the following call panics, it indicates UnimplementedNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_CreateWebhookEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWebhookEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateWebhookEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateWebhookEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateWebhookEndpoint(ctx, req.(*CreateWebhookEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_ListWebhookEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWebhookEndpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).ListWebhookEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_ListWebhookEndpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).ListWebhookEndpoints(ctx, req.(*ListWebhookEndpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_DeleteWebhookEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWebhookEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).DeleteWebhookEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_DeleteWebhookEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).DeleteWebhookEndpoint(ctx, req.(*DeleteWebhookEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetNotificationHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotificationHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetNotificationHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetNotificationHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetNotificationHistory(ctx, req.(*GetNotificationHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notifications.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWebhookEndpoint",
			Handler:    _NotificationService_CreateWebhookEndpoint_Handler,
		},
		{
			MethodName: "ListWebhookEndpoints",
			Handler:    _NotificationService_ListWebhookEndpoints_Handler,
		},
		{
			MethodName: "DeleteWebhookEndpoint",
			Handler:    _NotificationService_DeleteWebhookEndpoint_Handler,
		},
		{
			MethodName: "GetNotificationHistory",
			Handler:    _NotificationService_GetNotificationHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/notifications/notifications.proto",
}
