// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: proto/payments/payments.proto

package payments

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePaymentIntentRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Amount               int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ApplicationFeeAmount int64                  `protobuf:"varint,4,opt,name=application_fee_amount,json=applicationFeeAmount,proto3" json:"application_fee_amount,omitempty"`
	OnBehalfOf           string                 `protobuf:"bytes,5,opt,name=on_behalf_of,json=onBehalfOf,proto3" json:"on_behalf_of,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreatePaymentIntentRequest) Reset() {
	*x = CreatePaymentIntentRequest{}
	mi := &file_proto_payments_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentRequest) ProtoMessage() {}

func (x *CreatePaymentIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentIntentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentIntentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetApplicationFeeAmount() int64 {
	if x != nil {
		return x.ApplicationFeeAmount
	}
	return 0
}

func (x *CreatePaymentIntentRequest) GetOnBehalfOf() string {
	if x != nil {
		return x.OnBehalfOf
	}
	return ""
}

type ConfirmPaymentIntentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentMethodId string                 `protobuf:"bytes,2,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfirmPaymentIntentRequest) Reset() {
	*x = ConfirmPaymentIntentRequest{}
	mi := &file_proto_payments_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentIntentRequest) ProtoMessage() {}

func (x *ConfirmPaymentIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentIntentRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentIntentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{1}
}

func (x *ConfirmPaymentIntentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfirmPaymentIntentRequest) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

type RefundPaymentIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentIntentRequest) Reset() {
	*x = RefundPaymentIntentRequest{}
	mi := &file_proto_payments_payments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentIntentRequest) ProtoMessage() {}

func (x *RefundPaymentIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentIntentRequest.ProtoReflect.Descriptor instead.
func (*RefundPaymentIntentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{2}
}

func (x *RefundPaymentIntentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PaymentIntent struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount               int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Status               string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Description          string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	UserId               string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApplicationFeeAmount int64                  `protobuf:"varint,7,opt,name=application_fee_amount,json=applicationFeeAmount,proto3" json:"application_fee_amount,omitempty"`
	OnBehalfOf           string                 `protobuf:"bytes,8,opt,name=on_behalf_of,json=onBehalfOf,proto3" json:"on_behalf_of,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PaymentIntent) Reset() {
	*x = PaymentIntent{}
	mi := &file_proto_payments_payments_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentIntent) ProtoMessage() {}

func (x *PaymentIntent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payments_payments_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentIntent.ProtoReflect.Descriptor instead.
func (*PaymentIntent) Descriptor() ([]byte, []int) {
	return file_proto_payments_payments_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentIntent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentIntent) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentIntent) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentIntent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentIntent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PaymentIntent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentIntent) GetApplicationFeeAmount() int64 {
	if x != nil {
		return x.ApplicationFeeAmount
	}
	return 0
}

func (x *PaymentIntent) GetOnBehalfOf() string {
	if x != nil {
		return x.OnBehalfOf
	}
	return ""
}

func (x *PaymentIntent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_proto_payments_payments_proto protoreflect.FileDescriptor

const file_proto_payments_payments_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/payments/payments.proto\x12\bpayments\x1a\x1cgoogle/api/annotations.proto\"\xca\x01\n" +
	"\x1aCreatePaymentIntentRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x124\n" +
	"\x16application_fee_amount\x18\x04 \x01(\x03R\x14applicationFeeAmount\x12 \n" +
	"\fon_behalf_of\x18\x05 \x01(\tR\n" +
	"onBehalfOf\"Y\n" +
	"\x1bConfirmPaymentIntentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11payment_method_id\x18\x02 \x01(\tR\x0fpaymentMethodId\",\n" +
	"\x1aRefundPaymentIntentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9d\x02\n" +
	"\rPaymentIntent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x124\n" +
	"\x16application_fee_amount\x18\a \x01(\x03R\x14applicationFeeAmount\x12 \n" +
	"\fon_behalf_of\x18\b \x01(\tR\n" +
	"onBehalfOf\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt2\x92\x03\n" +
	"\x0ePaymentService\x12u\n" +
	"\x13CreatePaymentIntent\x12$.payments.CreatePaymentIntentRequest\x1a\x17.payments.PaymentIntent\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/payments/intents\x12\x84\x01\n" +
	"\x14ConfirmPaymentIntent\x12%.payments.ConfirmPaymentIntentRequest\x1a\x17.payments.PaymentIntent\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/payments/intents/{id}/confirm\x12\x81\x01\n" +
	"\x13RefundPaymentIntent\x12$.payments.RefundPaymentIntentRequest\x1a\x17.payments.PaymentIntent\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/payments/intents/{id}/refundB.Z,github.com/sapliy/sapliy-core/proto/paymentsb\x06proto3"

var (
	file_proto_payments_payments_proto_rawDescOnce sync.Once
	file_proto_payments_payments_proto_rawDescData []byte
)

func file_proto_payments_payments_proto_rawDescGZIP() []byte {
	file_proto_payments_payments_proto_rawDescOnce.Do(func() {
		file_proto_payments_payments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payments_payments_proto_rawDesc), len(file_proto_payments_payments_proto_rawDesc)))
	})
	return file_proto_payments_payments_proto_rawDescData
}

var file_proto_payments_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_payments_payments_proto_goTypes = []any{
	(*CreatePaymentIntentRequest)(nil),  // 0: payments.CreatePaymentIntentRequest
	(*ConfirmPaymentIntentRequest)(nil), // 1: payments.ConfirmPaymentIntentRequest
	(*RefundPaymentIntentRequest)(nil),  // 2: payments.RefundPaymentIntentRequest
	(*PaymentIntent)(nil),               // 3: payments.PaymentIntent
}
var file_proto_payments_payments_proto_depIdxs = []int32{
	0, // 0: payments.PaymentService.CreatePaymentIntent:input_type -> payments.CreatePaymentIntentRequest
	1, // 1: payments.PaymentService.ConfirmPaymentIntent:input_type -> payments.ConfirmPaymentIntentRequest
	2, // 2: payments.PaymentService.RefundPaymentIntent:input_type -> payments.RefundPaymentIntentRequest
	3, // 3: payments.PaymentService.CreatePaymentIntent:output_type -> payments.PaymentIntent
	3, // 4: payments.PaymentService.ConfirmPaymentIntent:output_type -> payments.PaymentIntent
	3, // 5: payments.PaymentService.RefundPaymentIntent:output_type -> payments.PaymentIntent
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_payments_payments_proto_init() }
func file_proto_payments_payments_proto_init() {
	if File_proto_payments_payments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payments_payments_proto_rawDesc), len(file_proto_payments_payments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payments_payments_proto_goTypes,
		DependencyIndexes: file_proto_payments_payments_proto_depIdxs,
		MessageInfos:      file_proto_payments_payments_proto_msgTypes,
	}.Build()
	File_proto_payments_payments_proto = out.File
	file_proto_payments_payments_proto_goTypes = nil
	file_proto_payments_payments_proto_depIdxs = nil
}
