// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/flow/flow.proto

package flow

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Flow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ZoneId        string                 `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	NodesJson     string                 `protobuf:"bytes,5,opt,name=nodes_json,json=nodesJson,proto3" json:"nodes_json,omitempty"` // Simplified for dynamic nodes
	EdgesJson     string                 `protobuf:"bytes,6,opt,name=edges_json,json=edgesJson,proto3" json:"edges_json,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flow) Reset() {
	*x = Flow{}
	mi := &file_proto_flow_flow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flow) ProtoMessage() {}

func (x *Flow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_flow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flow.ProtoReflect.Descriptor instead.
func (*Flow) Descriptor() ([]byte, []int) {
	return file_proto_flow_flow_proto_rawDescGZIP(), []int{0}
}

func (x *Flow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Flow) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *Flow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Flow) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Flow) GetNodesJson() string {
	if x != nil {
		return x.NodesJson
	}
	return ""
}

func (x *Flow) GetEdgesJson() string {
	if x != nil {
		return x.EdgesJson
	}
	return ""
}

func (x *Flow) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Flow) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type FlowExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FlowId        string                 `protobuf:"bytes,2,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "running", "completed", "failed", "paused"
	CurrentNodeId string                 `protobuf:"bytes,4,opt,name=current_node_id,json=currentNodeId,proto3" json:"current_node_id,omitempty"`
	InputJson     string                 `protobuf:"bytes,5,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,6,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	Steps         []*ExecutionStep       `protobuf:"bytes,7,rep,name=steps,proto3" json:"steps,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowExecution) Reset() {
	*x = FlowExecution{}
	mi := &file_proto_flow_flow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowExecution) ProtoMessage() {}

func (x *FlowExecution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_flow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowExecution.ProtoReflect.Descriptor instead.
func (*FlowExecution) Descriptor() ([]byte, []int) {
	return file_proto_flow_flow_proto_rawDescGZIP(), []int{1}
}

func (x *FlowExecution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FlowExecution) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *FlowExecution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FlowExecution) GetCurrentNodeId() string {
	if x != nil {
		return x.CurrentNodeId
	}
	return ""
}

func (x *FlowExecution) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *FlowExecution) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *FlowExecution) GetSteps() []*ExecutionStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *FlowExecution) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *FlowExecution) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type ExecutionStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	InputJson     string                 `protobuf:"bytes,3,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	OutputJson    string                 `protobuf:"bytes,4,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionStep) Reset() {
	*x = ExecutionStep{}
	mi := &file_proto_flow_flow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionStep) ProtoMessage() {}

func (x *ExecutionStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_flow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionStep.ProtoReflect.Descriptor instead.
func (*ExecutionStep) Descriptor() ([]byte, []int) {
	return file_proto_flow_flow_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionStep) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExecutionStep) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutionStep) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *ExecutionStep) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *ExecutionStep) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecutionStep) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type CreateFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NodesJson     string                 `protobuf:"bytes,3,opt,name=nodes_json,json=nodesJson,proto3" json:"nodes_json,omitempty"`
	EdgesJson     string                 `protobuf:"bytes,4,opt,name=edges_json,json=edgesJson,proto3" json:"edges_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFlowRequest) Reset() {
	*x = CreateFlowRequest{}
	mi := &file_proto_flow_flow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlowRequest) ProtoMessage() {}

func (x *CreateFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_flow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlowRequest.ProtoReflect.Descriptor instead.
func (*CreateFlowRequest) Descriptor() ([]byte, []int) {
	return file_proto_flow_flow_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFlowRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *CreateFlowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFlowRequest) GetNodesJson() string {
	if x != nil {
		return x.NodesJson
	}
	return ""
}

func (x *CreateFlowRequest) GetEdgesJson() string {
	if x != nil {
		return x.EdgesJson
	}
	return ""
}

type GetFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlowRequest) Reset() {
	*x = GetFlowRequest{}
	mi := &file_proto_flow_flow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlowRequest) ProtoMessage() {}

func (x *GetFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_flow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlowRequest.ProtoReflect.Descriptor instead.
func (*GetFlowRequest) Descriptor() ([]byte, []int) {
	return file_proto_flow_flow_proto_rawDescGZIP(), []int{4}
}

func (x *GetFlowRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListFlowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlowsRequest) Reset() {
	*x = ListFlowsRequest{}
	mi := &file_proto_flow_flow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlowsRequest) ProtoMessage() {}

func (x *ListFlowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_flow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlowsRequest.ProtoReflect.Descriptor instead.
func (*ListFlowsRequest) Descriptor() ([]byte, []int) {
	return file_proto_flow_flow_proto_rawDescGZIP(), []int{5}
}

func (x *ListFlowsRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

type ListFlowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flows         []*Flow                `protobuf:"bytes,1,rep,name=flows,proto3" json:"flows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlowsResponse) Reset() {
	*x = ListFlowsResponse{}
	mi := &file_proto_flow_flow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlowsResponse) ProtoMessage() {}

func (x *ListFlowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_flow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlowsResponse.ProtoReflect.Descriptor instead.
func (*ListFlowsResponse) Descriptor() ([]byte, []int) {
	return file_proto_flow_flow_proto_rawDescGZIP(), []int{6}
}

func (x *ListFlowsResponse) GetFlows() []*Flow {
	if x != nil {
		return x.Flows
	}
	return nil
}

type UpdateFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	NodesJson     string                 `protobuf:"bytes,4,opt,name=nodes_json,json=nodesJson,proto3" json:"nodes_json,omitempty"`
	EdgesJson     string                 `protobuf:"bytes,5,opt,name=edges_json,json=edgesJson,proto3" json:"edges_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFlowRequest) Reset() {
	*x = UpdateFlowRequest{}
	mi := &file_proto_flow_flow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFlowRequest) ProtoMessage() {}

func (x *UpdateFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_flow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFlowRequest.ProtoReflect.Descriptor instead.
func (*UpdateFlowRequest) Descriptor() ([]byte, []int) {
	return file_proto_flow_flow_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateFlowRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFlowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFlowRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpdateFlowRequest) GetNodesJson() string {
	if x != nil {
		return x.NodesJson
	}
	return ""
}

func (x *UpdateFlowRequest) GetEdgesJson() string {
	if x != nil {
		return x.EdgesJson
	}
	return ""
}

type BulkUpdateFlowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowIds       []string               `protobuf:"bytes,1,rep,name=flow_ids,json=flowIds,proto3" json:"flow_ids,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkUpdateFlowsRequest) Reset() {
	*x = BulkUpdateFlowsRequest{}
	mi := &file_proto_flow_flow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkUpdateFlowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkUpdateFlowsRequest) ProtoMessage() {}

func (x *BulkUpdateFlowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_flow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkUpdateFlowsRequest.ProtoReflect.Descriptor instead.
func (*BulkUpdateFlowsRequest) Descriptor() ([]byte, []int) {
	return file_proto_flow_flow_proto_rawDescGZIP(), []int{8}
}

func (x *BulkUpdateFlowsRequest) GetFlowIds() []string {
	if x != nil {
		return x.FlowIds
	}
	return nil
}

func (x *BulkUpdateFlowsRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type BulkUpdateFlowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedCount  int32                  `protobuf:"varint,1,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkUpdateFlowsResponse) Reset() {
	*x = BulkUpdateFlowsResponse{}
	mi := &file_proto_flow_flow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkUpdateFlowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkUpdateFlowsResponse) ProtoMessage() {}

func (x *BulkUpdateFlowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_flow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkUpdateFlowsResponse.ProtoReflect.Descriptor instead.
func (*BulkUpdateFlowsResponse) Descriptor() ([]byte, []int) {
	return file_proto_flow_flow_proto_rawDescGZIP(), []int{9}
}

func (x *BulkUpdateFlowsResponse) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

type GetExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionRequest) Reset() {
	*x = GetExecutionRequest{}
	mi := &file_proto_flow_flow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionRequest) ProtoMessage() {}

func (x *GetExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_flow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionRequest) Descriptor() ([]byte, []int) {
	return file_proto_flow_flow_proto_rawDescGZIP(), []int{10}
}

func (x *GetExecutionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResumeExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	OverridesJson string                 `protobuf:"bytes,2,opt,name=overrides_json,json=overridesJson,proto3" json:"overrides_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeExecutionRequest) Reset() {
	*x = ResumeExecutionRequest{}
	mi := &file_proto_flow_flow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeExecutionRequest) ProtoMessage() {}

func (x *ResumeExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_flow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeExecutionRequest.ProtoReflect.Descriptor instead.
func (*ResumeExecutionRequest) Descriptor() ([]byte, []int) {
	return file_proto_flow_flow_proto_rawDescGZIP(), []int{11}
}

func (x *ResumeExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ResumeExecutionRequest) GetOverridesJson() string {
	if x != nil {
		return x.OverridesJson
	}
	return ""
}

type ResumeExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeExecutionResponse) Reset() {
	*x = ResumeExecutionResponse{}
	mi := &file_proto_flow_flow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeExecutionResponse) ProtoMessage() {}

func (x *ResumeExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flow_flow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeExecutionResponse.ProtoReflect.Descriptor instead.
func (*ResumeExecutionResponse) Descriptor() ([]byte, []int) {
	return file_proto_flow_flow_proto_rawDescGZIP(), []int{12}
}

func (x *ResumeExecutionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_flow_flow_proto protoreflect.FileDescriptor

const file_proto_flow_flow_proto_rawDesc = "" +
	"\n" +
	"\x15proto/flow/flow.proto\x12\x04flow\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x02\n" +
	"\x04Flow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\azone_id\x18\x02 \x01(\tR\x06zoneId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"nodes_json\x18\x05 \x01(\tR\tnodesJson\x12\x1d\n" +
	"\n" +
	"edges_json\x18\x06 \x01(\tR\tedgesJson\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xdf\x02\n" +
	"\rFlowExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aflow_id\x18\x02 \x01(\tR\x06flowId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12&\n" +
	"\x0fcurrent_node_id\x18\x04 \x01(\tR\rcurrentNodeId\x12\x1d\n" +
	"\n" +
	"input_json\x18\x05 \x01(\tR\tinputJson\x12#\n" +
	"\rmetadata_json\x18\x06 \x01(\tR\fmetadataJson\x12)\n" +
	"\x05steps\x18\a \x03(\v2\x13.flow.ExecutionStepR\x05steps\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"\xd1\x01\n" +
	"\rExecutionStep\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"input_json\x18\x03 \x01(\tR\tinputJson\x12\x1f\n" +
	"\voutput_json\x18\x04 \x01(\tR\n" +
	"outputJson\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"~\n" +
	"\x11CreateFlowRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"nodes_json\x18\x03 \x01(\tR\tnodesJson\x12\x1d\n" +
	"\n" +
	"edges_json\x18\x04 \x01(\tR\tedgesJson\" \n" +
	"\x0eGetFlowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x10ListFlowsRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\"5\n" +
	"\x11ListFlowsResponse\x12 \n" +
	"\x05flows\x18\x01 \x03(\v2\n" +
	".flow.FlowR\x05flows\"\x8f\x01\n" +
	"\x11UpdateFlowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"nodes_json\x18\x04 \x01(\tR\tnodesJson\x12\x1d\n" +
	"\n" +
	"edges_json\x18\x05 \x01(\tR\tedgesJson\"M\n" +
	"\x16BulkUpdateFlowsRequest\x12\x19\n" +
	"\bflow_ids\x18\x01 \x03(\tR\aflowIds\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\">\n" +
	"\x17BulkUpdateFlowsResponse\x12#\n" +
	"\rupdated_count\x18\x01 \x01(\x05R\fupdatedCount\"%\n" +
	"\x13GetExecutionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"b\n" +
	"\x16ResumeExecutionRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12%\n" +
	"\x0eoverrides_json\x18\x02 \x01(\tR\roverridesJson\"1\n" +
	"\x17ResumeExecutionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x97\x05\n" +
	"\vFlowService\x12G\n" +
	"\n" +
	"CreateFlow\x12\x17.flow.CreateFlowRequest\x1a\n" +
	".flow.Flow\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/flows\x12C\n" +
	"\aGetFlow\x12\x14.flow.GetFlowRequest\x1a\n" +
	".flow.Flow\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/flows/{id}\x12O\n" +
	"\tListFlows\x12\x16.flow.ListFlowsRequest\x1a\x17.flow.ListFlowsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/flows\x12L\n" +
	"\n" +
	"UpdateFlow\x12\x17.flow.UpdateFlowRequest\x1a\n" +
	".flow.Flow\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/flows/{id}\x12p\n" +
	"\x0fBulkUpdateFlows\x12\x1c.flow.BulkUpdateFlowsRequest\x1a\x1d.flow.BulkUpdateFlowsResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/flows/bulk-update\x12a\n" +
	"\fGetExecution\x12\x19.flow.GetExecutionRequest\x1a\x13.flow.FlowExecution\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/flows/executions/{id}\x12\x85\x01\n" +
	"\x0fResumeExecution\x12\x1c.flow.ResumeExecutionRequest\x1a\x1d.flow.ResumeExecutionResponse\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/v1/flows/executions/{execution_id}/resumeB0Z.github.com/sapliy/sapliy-core/proto/flowb\x06proto3"

var (
	file_proto_flow_flow_proto_rawDescOnce sync.Once
	file_proto_flow_flow_proto_rawDescData []byte
)

func file_proto_flow_flow_proto_rawDescGZIP() []byte {
	file_proto_flow_flow_proto_rawDescOnce.Do(func() {
		file_proto_flow_flow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_flow_flow_proto_rawDesc), len(file_proto_flow_flow_proto_rawDesc)))
	})
	return file_proto_flow_flow_proto_rawDescData
}

var file_proto_flow_flow_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_flow_flow_proto_goTypes = []any{
	(*Flow)(nil),                    // 0: flow.Flow
	(*FlowExecution)(nil),           // 1: flow.FlowExecution
	(*ExecutionStep)(nil),           // 2: flow.ExecutionStep
	(*CreateFlowRequest)(nil),       // 3: flow.CreateFlowRequest
	(*GetFlowRequest)(nil),          // 4: flow.GetFlowRequest
	(*ListFlowsRequest)(nil),        // 5: flow.ListFlowsRequest
	(*ListFlowsResponse)(nil),       // 6: flow.ListFlowsResponse
	(*UpdateFlowRequest)(nil),       // 7: flow.UpdateFlowRequest
	(*BulkUpdateFlowsRequest)(nil),  // 8: flow.BulkUpdateFlowsRequest
	(*BulkUpdateFlowsResponse)(nil), // 9: flow.BulkUpdateFlowsResponse
	(*GetExecutionRequest)(nil),     // 10: flow.GetExecutionRequest
	(*ResumeExecutionRequest)(nil),  // 11: flow.ResumeExecutionRequest
	(*ResumeExecutionResponse)(nil), // 12: flow.ResumeExecutionResponse
	(*timestamppb.Timestamp)(nil),   // 13: google.protobuf.Timestamp
}
var file_proto_flow_flow_proto_depIdxs = []int32{
	13, // 0: flow.Flow.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: flow.Flow.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 2: flow.FlowExecution.steps:type_name -> flow.ExecutionStep
	13, // 3: flow.FlowExecution.started_at:type_name -> google.protobuf.Timestamp
	13, // 4: flow.FlowExecution.finished_at:type_name -> google.protobuf.Timestamp
	13, // 5: flow.ExecutionStep.started_at:type_name -> google.protobuf.Timestamp
	0,  // 6: flow.ListFlowsResponse.flows:type_name -> flow.Flow
	3,  // 7: flow.FlowService.CreateFlow:input_type -> flow.CreateFlowRequest
	4,  // 8: flow.FlowService.GetFlow:input_type -> flow.GetFlowRequest
	5,  // 9: flow.FlowService.ListFlows:input_type -> flow.ListFlowsRequest
	7,  // 10: flow.FlowService.UpdateFlow:input_type -> flow.UpdateFlowRequest
	8,  // 11: flow.FlowService.BulkUpdateFlows:input_type -> flow.BulkUpdateFlowsRequest
	10, // 12: flow.FlowService.GetExecution:input_type -> flow.GetExecutionRequest
	11, // 13: flow.FlowService.ResumeExecution:input_type -> flow.ResumeExecutionRequest
	0,  // 14: flow.FlowService.CreateFlow:output_type -> flow.Flow
	0,  // 15: flow.FlowService.GetFlow:output_type -> flow.Flow
	6,  // 16: flow.FlowService.ListFlows:output_type -> flow.ListFlowsResponse
	0,  // 17: flow.FlowService.UpdateFlow:output_type -> flow.Flow
	9,  // 18: flow.FlowService.BulkUpdateFlows:output_type -> flow.BulkUpdateFlowsResponse
	1,  // 19: flow.FlowService.GetExecution:output_type -> flow.FlowExecution
	12, // 20: flow.FlowService.ResumeExecution:output_type -> flow.ResumeExecutionResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_flow_flow_proto_init() }
func file_proto_flow_flow_proto_init() {
	if File_proto_flow_flow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_flow_flow_proto_rawDesc), len(file_proto_flow_flow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_flow_flow_proto_goTypes,
		DependencyIndexes: file_proto_flow_flow_proto_depIdxs,
		MessageInfos:      file_proto_flow_flow_proto_msgTypes,
	}.Build()
	File_proto_flow_flow_proto = out.File
	file_proto_flow_flow_proto_goTypes = nil
	file_proto_flow_flow_proto_depIdxs = nil
}
